project:
  type: website
  output-dir: docs

website: 
  title: "Computational Models for Complex system"
  navbar:
    search: true
    right:
      - href: index.md
        text: Home
      - text: "Site Map"
        menu:
          - text: "Analysis of long-range ecological models"
            href: ./notebooks/long_range_simulations.ipynb
          - text: "Analysis of ecological lattice models"
            href: ./notebooks/lattice_simulations.ipynb
          - text: "Analysis of the Repressilator model"
            href: ./notebooks/repressilator.ipynb
      - icon: github
        href: https://github.com/iretes/rock-scissors-paper
  
  page-footer: 
    left: "© 2024 Irene Testa. This project was developed for the “Computational Models for Complex Systems” course at the University of Pisa (a.y. 2023/2024)."

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
    tools:
      theme-toggle: true

editor: visual