project:
  type: website
  output-dir: docs

website: 
  title: "Computational Models for Complex system"
  navbar:
    search: true
    right:
      - href: index.md
        text: Home
      - text: "Site Map"
        menu:
          - text: "Long range model analysis"
            href: ./notebooks/long_range_simulations.ipynb
          - text: "Lattice model analysis"
            href: ./notebooks/lattice_simulations.ipynb
      - icon: github
        href: https://github.com/iretes/rock-scissors-paper
  
  page-footer: 
    left: "© 2024 Irene Testa"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-location: left
    tools:
      theme-toggle: true

editor: visual