project:
  type: website
  output-dir: docs

website: 
  title: "Computational Models for Complex system"
  navbar:
    search: true
    right:
      - href: index.md
        text: Home
      - icon: github
        href: https://github.com/iretes/rock-scissors-paper
  
  page-footer: 
    left: "© 2024 Irene Testa"

format:
  html:
    theme: cosmo dark
    toc: true
    toc-location: left

editor: visual